### ISSUE TITLE
Funked up Ethiopic Ex B?

### ISSUE THREAD

**Issue by Mercury13** [notofonts/ethiopic#6]
### Title 
  Ethiopic Ex B disappeared from font

### Font 
NotoSerifEthiopic-Regular.ttf

### Where the font came from, and when
Site: this repo
Date: 2022-04-19

### Font Version
2.100

### OS name and version
All OS

### Application name and version
All apps

### Issue
Disappeared Ethiopic ex B

### Character data
U+1E7E0 Ethiopic syllable Hhya
…
U+1E7FE Ethiopic syllable Gurage Pwee

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/163970533-71a1eda2-e340-4699-ab1c-b40e11d0ea6d.png)

**Comment by dyacob** [comment]
As a reference for the PR that would have included the glyphs:  https://github.com/googlefonts/noto-source/pull/408

**Comment by Mercury13** [comment]
Still funked up in 2.101.

**Comment by NeilSureshPatel** [comment]
I don't know if these disappeared during the repo migration, but I still have the UFO sources in my fork from back when we added the Gurage characters.

[NeilSureshPatel/NotoSansEthiopic](https://github.com/NeilSureshPatel/noto-source/tree/master/src/NotoSansEthiopic)
[NeilSureshPatel/NotoSerifEthiopic](https://github.com/NeilSureshPatel/noto-source/tree/master/src/NotoSerifEthiopic)

**Comment by Mercury13** [comment]
> I don't know if these disappeared during the repo migration, but I still have the UFO sources in my fork from back when we added the Gurage characters.

No, they disappeared before, in 2.100.

**Comment by NeilSureshPatel** [comment]
Ahh, I found when it happened. It was when the UFO sources were converted to Glyphs sources. 
[8e001ee9e64fc130112963386cc9eb25a19c39cc](https://github.com/googlefonts/noto-source/commit/8e001ee9e64fc130112963386cc9eb25a19c39cc)

You can see the Gurage .glif files are removed from the directory when the Glyphs source file is uploaded. The new Glyphs source file does not have any of the Gurage glyphs in it.

**Comment by dyacob** [comment]
With @NeilSureshPatel having identified where the break occurred, does the team have enough info to generate a new release, a v2.102 ?  Does a conversion utility need to get fixed so the Extended-B .glif files don't get deleted again?  We might need a new ticket for that utility.  

@marekjez86 , are you able to generate a new release based on the info provided?

**Comment by dyacob** [comment]
This issue came closer to resolution today, but there appears to be a hiccup in the `CheckWithFontbakery` action related to version numbers:  https://github.com/notofonts/ethiopic/actions/runs/3378933454/jobs/5609975131#step:7:72  

Is someone already looking into it, or who should be notified?

**Comment by marekjez86** [comment]
@dyacob : we know about the hiccup. I believe @moyogo will work on this

**Comment by Mercury13** [comment]
What’s remaining? Some auto-checks?

**Comment by dyacob** [comment]
@Mercury13  v2.102 for both Serif and Sans Serif can be downloaded now and includes the missing glyphs.  The two archives appear to have a total of 388 `.ttf` and `.otf` files.  Pretty fantastic!  Thanks for pointing out the original issue, and thanks to @moyogo and everyone else in this thread for getting the problem resolved and the release out!

I believe this issue can now be closed.
