### ISSUE TITLE
How to check if you updated something?

### ISSUE THREAD

**Issue by Mercury13** [notofonts/ethiopic#8]
**Is your feature request related to a problem? Please describe.**
When your fonts were at https://github.com/notofonts/noto-fonts, it was easy: I checked date of `hinted` directory, and if it changed, I checked what you’ve done and if I should update my fonts. What to do now?

First I was glad that you made another such hub, https://github.com/notofonts/notofonts.github.io, but it contains a tiny fraction of your fonts.

Thanks in advance.

**Comment by simoncozens** [comment]
When fonts are updated:
1) They get a release in their script-specific repository.
2) They get automatically copied to the notofonts.github.io repository.

The notofonts.github.io repository will have roughly the same structure as the old noto-fonts repo. The only reason it doesn't contain all the fonts yet is that fonts are only copied when they are updated. I am working on updating all the fonts and so the repository will be fully populated over the next few months. There is also a JSON file at https://notofonts.github.io/noto.json with release metadata.
